// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_padding_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class JsonPaddingBuilder extends _JsonPaddingBuilder {
  const JsonPaddingBuilder({required super.args});

  static const kType = 'padding';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static JsonPaddingBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => JsonPaddingBuilder(args: map);

  @override
  JsonPaddingBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = JsonPaddingBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  Padding buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return Padding(
      key: key,
      padding: model.padding,
      child: model.child?.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonPadding extends JsonWidgetData {
  JsonPadding({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    required this.padding,
    this.child,
  }) : super(
         jsonWidgetArgs: JsonPaddingBuilderModel.fromDynamic(
           {'padding': padding, 'child': child, ...args},
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder:
             () => JsonPaddingBuilder(
               args: JsonPaddingBuilderModel.fromDynamic(
                 {'padding': padding, 'child': child, ...args},
                 args: args,
                 registry: registry,
               ),
             ),
         jsonWidgetType: JsonPaddingBuilder.kType,
       );

  /* AUTOGENERATED FROM [Padding.padding]*/
  /// The amount of space by which to inset the child.
  final EdgeInsetsGeometry padding;

  final JsonWidgetData? child;
}

/* AUTOGENERATED FROM [Padding]*/
/// Creates a widget that insets its child.
class JsonPaddingBuilderModel extends JsonWidgetBuilderModel {
  const JsonPaddingBuilderModel(
    super.args, {
    required this.padding,
    this.child,
  });

  /* AUTOGENERATED FROM [Padding.padding]*/
  /// The amount of space by which to inset the child.
  final EdgeInsetsGeometry padding;

  final JsonWidgetData? child;

  static JsonPaddingBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[JsonPaddingBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static JsonPaddingBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    JsonPaddingBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is JsonPaddingBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = JsonPaddingBuilderModel(
          args,
          padding: () {
            dynamic parsed = ThemeDecoder.decodeEdgeInsetsGeometry(
              map['padding'],
              validate: false,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [padding].',
              );
            }
            return parsed;
          }(),
          child: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['child'],
              registry: registry,
            );

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'padding': ThemeEncoder.encodeEdgeInsetsGeometry(padding),
      'child': child?.toJson(),

      ...args,
    });
  }
}

class PaddingSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/padding.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'Padding',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'padding': SchemaHelper.objectSchema(EdgeInsetsGeometrySchema.id),
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
    'required': ['padding'],
  };
}
