// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_offstage_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class JsonOffstageBuilder extends _JsonOffstageBuilder {
  const JsonOffstageBuilder({required super.args});

  static const kType = 'offstage';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static JsonOffstageBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => JsonOffstageBuilder(args: map);

  @override
  JsonOffstageBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = JsonOffstageBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  Offstage buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return Offstage(
      key: key,
      offstage: model.offstage,
      child: model.child?.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonOffstage extends JsonWidgetData {
  JsonOffstage({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.offstage = true,
    this.child,
  }) : super(
         jsonWidgetArgs: JsonOffstageBuilderModel.fromDynamic(
           {'offstage': offstage, 'child': child, ...args},
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder:
             () => JsonOffstageBuilder(
               args: JsonOffstageBuilderModel.fromDynamic(
                 {'offstage': offstage, 'child': child, ...args},
                 args: args,
                 registry: registry,
               ),
             ),
         jsonWidgetType: JsonOffstageBuilder.kType,
       );

  /* AUTOGENERATED FROM [Offstage.offstage]*/
  /// Whether the child is hidden from the rest of the tree.
  ///
  /// If true, the child is laid out as if it was in the tree, but without
  /// painting anything, without making the child available for hit testing, and
  /// without taking any room in the parent.
  ///
  /// Offstage children are still active: they can receive focus and have keyboard
  /// input directed to them.
  ///
  /// Animations continue to run in offstage children, and therefore use battery
  /// and CPU time, regardless of whether the animations end up being visible.
  ///
  /// If false, the child is included in the tree as normal.
  final bool offstage;

  final JsonWidgetData? child;
}

/* AUTOGENERATED FROM [Offstage]*/
/// Creates a widget that visually hides its child.
class JsonOffstageBuilderModel extends JsonWidgetBuilderModel {
  const JsonOffstageBuilderModel(
    super.args, {
    this.offstage = true,
    this.child,
  });

  /* AUTOGENERATED FROM [Offstage.offstage]*/
  /// Whether the child is hidden from the rest of the tree.
  ///
  /// If true, the child is laid out as if it was in the tree, but without
  /// painting anything, without making the child available for hit testing, and
  /// without taking any room in the parent.
  ///
  /// Offstage children are still active: they can receive focus and have keyboard
  /// input directed to them.
  ///
  /// Animations continue to run in offstage children, and therefore use battery
  /// and CPU time, regardless of whether the animations end up being visible.
  ///
  /// If false, the child is included in the tree as normal.
  final bool offstage;

  final JsonWidgetData? child;

  static JsonOffstageBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[JsonOffstageBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static JsonOffstageBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    JsonOffstageBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is JsonOffstageBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = JsonOffstageBuilderModel(
          args,
          offstage: JsonClass.parseBool(map['offstage'], whenNull: true),
          child: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['child'],
              registry: registry,
            );

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'offstage': true == offstage ? null : offstage,
      'child': child?.toJson(),

      ...args,
    });
  }
}

class OffstageSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/offstage.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'Offstage',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'offstage': SchemaHelper.boolSchema,
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
    'required': [],
  };
}
