// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_icon_theme_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class JsonIconThemeBuilder extends _JsonIconThemeBuilder {
  const JsonIconThemeBuilder({required super.args});

  static const kType = 'icon_theme';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static JsonIconThemeBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => JsonIconThemeBuilder(args: map);

  @override
  JsonIconThemeBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = JsonIconThemeBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  IconTheme buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return IconTheme(
      data: model.data,
      key: key,
      child: model.child.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonIconTheme extends JsonWidgetData {
  JsonIconTheme({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    required this.data,
    required this.child,
  }) : super(
         jsonWidgetArgs: JsonIconThemeBuilderModel.fromDynamic(
           {'data': data, 'child': child, ...args},
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder:
             () => JsonIconThemeBuilder(
               args: JsonIconThemeBuilderModel.fromDynamic(
                 {'data': data, 'child': child, ...args},
                 args: args,
                 registry: registry,
               ),
             ),
         jsonWidgetType: JsonIconThemeBuilder.kType,
       );

  /* AUTOGENERATED FROM [IconTheme.data]*/
  /// The set of properties to use for icons in this subtree.
  final IconThemeData data;

  final JsonWidgetData child;
}

/* AUTOGENERATED FROM [IconTheme]*/
/// Creates an icon theme that controls properties of descendant widgets.
class JsonIconThemeBuilderModel extends JsonWidgetBuilderModel {
  const JsonIconThemeBuilderModel(
    super.args, {
    required this.data,
    required this.child,
  });

  /* AUTOGENERATED FROM [IconTheme.data]*/
  /// The set of properties to use for icons in this subtree.
  final IconThemeData data;

  final JsonWidgetData child;

  static JsonIconThemeBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[JsonIconThemeBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static JsonIconThemeBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    JsonIconThemeBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is JsonIconThemeBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = JsonIconThemeBuilderModel(
          args,
          data: () {
            dynamic parsed = ThemeDecoder.decodeIconThemeData(
              map['data'],
              validate: false,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [data].',
              );
            }
            return parsed;
          }(),
          child: () {
            dynamic parsed = JsonWidgetData.fromDynamic(
              map['child'],
              registry: registry,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [child].',
              );
            }
            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'data': ThemeEncoder.encodeIconThemeData(data),
      'child': child.toJson(),

      ...args,
    });
  }
}

class IconThemeSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/icon_theme.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'IconTheme',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'data': SchemaHelper.objectSchema(IconThemeDataSchema.id),
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
    'required': ['data', 'child'],
  };
}
