// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_expanded_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class JsonExpandedBuilder extends _JsonExpandedBuilder {
  const JsonExpandedBuilder({required super.args});

  static const kType = 'expanded';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static JsonExpandedBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => JsonExpandedBuilder(args: map);

  @override
  JsonExpandedBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = JsonExpandedBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  Expanded buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return Expanded(
      flex: model.flex,
      key: key,
      child: model.child.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonExpanded extends JsonWidgetData {
  JsonExpanded({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.flex = 1,
    required this.child,
  }) : super(
         jsonWidgetArgs: JsonExpandedBuilderModel.fromDynamic(
           {'flex': flex, 'child': child, ...args},
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder:
             () => JsonExpandedBuilder(
               args: JsonExpandedBuilderModel.fromDynamic(
                 {'flex': flex, 'child': child, ...args},
                 args: args,
                 registry: registry,
               ),
             ),
         jsonWidgetType: JsonExpandedBuilder.kType,
       );

  final int flex;

  final JsonWidgetData child;
}

/* AUTOGENERATED FROM [Expanded]*/
/// Creates a widget that expands a child of a [Row], [Column], or [Flex]
/// so that the child fills the available space along the flex widget's
/// main axis.
class JsonExpandedBuilderModel extends JsonWidgetBuilderModel {
  const JsonExpandedBuilderModel(
    super.args, {
    this.flex = 1,
    required this.child,
  });

  final int flex;

  final JsonWidgetData child;

  static JsonExpandedBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[JsonExpandedBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static JsonExpandedBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    JsonExpandedBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is JsonExpandedBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = JsonExpandedBuilderModel(
          args,
          flex: () {
            dynamic parsed = JsonClass.maybeParseInt(map['flex']);

            parsed ??= 1;

            return parsed;
          }(),
          child: () {
            dynamic parsed = JsonWidgetData.fromDynamic(
              map['child'],
              registry: registry,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [child].',
              );
            }
            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'flex': 1 == flex ? null : flex,
      'child': child.toJson(),

      ...args,
    });
  }
}

class ExpandedSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/expanded.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'Expanded',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'flex': SchemaHelper.numberSchema,
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
    'required': ['child'],
  };
}
