// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_animated_theme_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class JsonAnimatedThemeBuilder extends _JsonAnimatedThemeBuilder {
  const JsonAnimatedThemeBuilder({required super.args});

  static const kType = 'animated_theme';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static JsonAnimatedThemeBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => JsonAnimatedThemeBuilder(args: map);

  @override
  JsonAnimatedThemeBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = JsonAnimatedThemeBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  AnimatedTheme buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return AnimatedTheme(
      curve: model.curve,
      data: model.data,
      duration: model.duration,
      key: key,
      onEnd: model.onEnd,
      child: model.child.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonAnimatedTheme extends JsonWidgetData {
  JsonAnimatedTheme({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.curve = Curves.linear,
    required this.data,
    this.duration = kThemeAnimationDuration,
    this.onEnd,
    required this.child,
  }) : super(
         jsonWidgetArgs: JsonAnimatedThemeBuilderModel.fromDynamic(
           {
             'curve': curve,
             'data': data,
             'duration': duration,
             'onEnd': onEnd,
             'child': child,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder:
             () => JsonAnimatedThemeBuilder(
               args: JsonAnimatedThemeBuilderModel.fromDynamic(
                 {
                   'curve': curve,
                   'data': data,
                   'duration': duration,
                   'onEnd': onEnd,
                   'child': child,

                   ...args,
                 },
                 args: args,
                 registry: registry,
               ),
             ),
         jsonWidgetType: JsonAnimatedThemeBuilder.kType,
       );

  final Curve curve;

  /* AUTOGENERATED FROM [AnimatedTheme.data]*/
  /// Specifies the color and typography values for descendant widgets.
  final ThemeData data;

  final Duration duration;

  final void Function()? onEnd;

  /* AUTOGENERATED FROM [AnimatedTheme.child]*/
  /// The widget below this widget in the tree.
  ///
  /// {@macro flutter.widgets.ProxyWidget.child}
  final JsonWidgetData child;
}

/* AUTOGENERATED FROM [AnimatedTheme]*/
/// Creates an animated theme.
///
/// By default, the theme transition uses a linear curve.
class JsonAnimatedThemeBuilderModel extends JsonWidgetBuilderModel {
  const JsonAnimatedThemeBuilderModel(
    super.args, {
    this.curve = Curves.linear,
    required this.data,
    this.duration = kThemeAnimationDuration,
    this.onEnd,
    required this.child,
  });

  final Curve curve;

  /* AUTOGENERATED FROM [AnimatedTheme.data]*/
  /// Specifies the color and typography values for descendant widgets.
  final ThemeData data;

  final Duration duration;

  final void Function()? onEnd;

  /* AUTOGENERATED FROM [AnimatedTheme.child]*/
  /// The widget below this widget in the tree.
  ///
  /// {@macro flutter.widgets.ProxyWidget.child}
  final JsonWidgetData child;

  static JsonAnimatedThemeBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[JsonAnimatedThemeBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static JsonAnimatedThemeBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    JsonAnimatedThemeBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is JsonAnimatedThemeBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = JsonAnimatedThemeBuilderModel(
          args,
          curve: () {
            dynamic parsed = CurvesValues.lookup(map['curve']);

            parsed ??= Curves.linear;

            return parsed;
          }(),
          data: () {
            dynamic parsed = ThemeDecoder.decodeThemeData(
              map['data'],
              validate: false,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [data].',
              );
            }
            return parsed;
          }(),
          duration: () {
            dynamic parsed = JsonClass.maybeParseDurationFromMillis(
              map['duration'],
            );

            parsed ??= kThemeAnimationDuration;

            return parsed;
          }(),
          onEnd: map['onEnd'],
          child: () {
            dynamic parsed = JsonWidgetData.fromDynamic(
              map['child'],
              registry: registry,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [child].',
              );
            }
            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'curve': Curves.linear == curve ? null : CurvesValues.encode(curve),
      'data': ThemeEncoder.encodeThemeData(data),
      'duration':
          kThemeAnimationDuration == duration ? null : duration.inMilliseconds,
      'onEnd': onEnd,
      'child': child.toJson(),

      ...args,
    });
  }
}

class AnimatedThemeSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/animated_theme.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'AnimatedTheme',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'curve': SchemaHelper.anySchema,
      'data': SchemaHelper.objectSchema(ThemeDataSchema.id),
      'duration': SchemaHelper.anySchema,
      'onEnd': SchemaHelper.anySchema,
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
    'required': ['data', 'child'],
  };
}
