// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_center_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class JsonCenterBuilder extends _JsonCenterBuilder {
  const JsonCenterBuilder({required super.args});

  static const kType = 'center';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static JsonCenterBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => JsonCenterBuilder(args: map);

  @override
  JsonCenterBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = JsonCenterBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  Center buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return Center(
      heightFactor: model.heightFactor,
      key: key,
      widthFactor: model.widthFactor,
      child: model.child?.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonCenter extends JsonWidgetData {
  JsonCenter({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.heightFactor,
    this.widthFactor,
    this.child,
  }) : super(
         jsonWidgetArgs: JsonCenterBuilderModel.fromDynamic(
           {
             'heightFactor': heightFactor,
             'widthFactor': widthFactor,
             'child': child,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder:
             () => JsonCenterBuilder(
               args: JsonCenterBuilderModel.fromDynamic(
                 {
                   'heightFactor': heightFactor,
                   'widthFactor': widthFactor,
                   'child': child,

                   ...args,
                 },
                 args: args,
                 registry: registry,
               ),
             ),
         jsonWidgetType: JsonCenterBuilder.kType,
       );

  final double? heightFactor;

  final double? widthFactor;

  final JsonWidgetData? child;
}

/* AUTOGENERATED FROM [Center]*/
/// Creates a widget that centers its child.
class JsonCenterBuilderModel extends JsonWidgetBuilderModel {
  const JsonCenterBuilderModel(
    super.args, {
    this.heightFactor,
    this.widthFactor,
    this.child,
  });

  final double? heightFactor;

  final double? widthFactor;

  final JsonWidgetData? child;

  static JsonCenterBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[JsonCenterBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static JsonCenterBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    JsonCenterBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is JsonCenterBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = JsonCenterBuilderModel(
          args,
          heightFactor: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['heightFactor']);

            return parsed;
          }(),
          widthFactor: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['widthFactor']);

            return parsed;
          }(),
          child: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['child'],
              registry: registry,
            );

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'heightFactor': heightFactor,
      'widthFactor': widthFactor,
      'child': child?.toJson(),

      ...args,
    });
  }
}

class CenterSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/center.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'Center',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'heightFactor': SchemaHelper.numberSchema,
      'widthFactor': SchemaHelper.numberSchema,
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
    'required': [],
  };
}
