// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_directionality_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class JsonDirectionalityBuilder extends _JsonDirectionalityBuilder {
  const JsonDirectionalityBuilder({required super.args});

  static const kType = 'directionality';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static JsonDirectionalityBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => JsonDirectionalityBuilder(args: map);

  @override
  JsonDirectionalityBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = JsonDirectionalityBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  Directionality buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return Directionality(
      key: key,
      textDirection: model.textDirection,
      child: model.child.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonDirectionality extends JsonWidgetData {
  JsonDirectionality({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    required this.textDirection,
    required this.child,
  }) : super(
         jsonWidgetArgs: JsonDirectionalityBuilderModel.fromDynamic(
           {'textDirection': textDirection, 'child': child, ...args},
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder:
             () => JsonDirectionalityBuilder(
               args: JsonDirectionalityBuilderModel.fromDynamic(
                 {'textDirection': textDirection, 'child': child, ...args},
                 args: args,
                 registry: registry,
               ),
             ),
         jsonWidgetType: JsonDirectionalityBuilder.kType,
       );

  /* AUTOGENERATED FROM [Directionality.textDirection]*/
  /// The text direction for this subtree.
  final TextDirection textDirection;

  final JsonWidgetData child;
}

/* AUTOGENERATED FROM [Directionality]*/
/// Creates a widget that determines the directionality of text and
/// text-direction-sensitive render objects.
class JsonDirectionalityBuilderModel extends JsonWidgetBuilderModel {
  const JsonDirectionalityBuilderModel(
    super.args, {
    required this.textDirection,
    required this.child,
  });

  /* AUTOGENERATED FROM [Directionality.textDirection]*/
  /// The text direction for this subtree.
  final TextDirection textDirection;

  final JsonWidgetData child;

  static JsonDirectionalityBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[JsonDirectionalityBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static JsonDirectionalityBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    JsonDirectionalityBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is JsonDirectionalityBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = JsonDirectionalityBuilderModel(
          args,
          textDirection: () {
            dynamic parsed = ThemeDecoder.decodeTextDirection(
              map['textDirection'],
              validate: false,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [textDirection].',
              );
            }
            return parsed;
          }(),
          child: () {
            dynamic parsed = JsonWidgetData.fromDynamic(
              map['child'],
              registry: registry,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [child].',
              );
            }
            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'textDirection': ThemeEncoder.encodeTextDirection(textDirection),
      'child': child.toJson(),

      ...args,
    });
  }
}

class DirectionalitySchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/directionality.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'Directionality',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'textDirection': SchemaHelper.objectSchema(TextDirectionSchema.id),
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
    'required': ['textDirection', 'child'],
  };
}
