// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_limited_box_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class JsonLimitedBoxBuilder extends _JsonLimitedBoxBuilder {
  const JsonLimitedBoxBuilder({required super.args});

  static const kType = 'limited_box';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static JsonLimitedBoxBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => JsonLimitedBoxBuilder(args: map);

  @override
  JsonLimitedBoxBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = JsonLimitedBoxBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  LimitedBox buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return LimitedBox(
      key: key,
      maxHeight: model.maxHeight,
      maxWidth: model.maxWidth,
      child: model.child?.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonLimitedBox extends JsonWidgetData {
  JsonLimitedBox({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.maxHeight = double.infinity,
    this.maxWidth = double.infinity,
    this.child,
  }) : super(
         jsonWidgetArgs: JsonLimitedBoxBuilderModel.fromDynamic(
           {
             'maxHeight': maxHeight,
             'maxWidth': maxWidth,
             'child': child,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder:
             () => JsonLimitedBoxBuilder(
               args: JsonLimitedBoxBuilderModel.fromDynamic(
                 {
                   'maxHeight': maxHeight,
                   'maxWidth': maxWidth,
                   'child': child,

                   ...args,
                 },
                 args: args,
                 registry: registry,
               ),
             ),
         jsonWidgetType: JsonLimitedBoxBuilder.kType,
       );

  /* AUTOGENERATED FROM [LimitedBox.maxHeight]*/
  /// The maximum height limit to apply in the absence of a
  /// [BoxConstraints.maxHeight] constraint.
  final double maxHeight;

  /* AUTOGENERATED FROM [LimitedBox.maxWidth]*/
  /// The maximum width limit to apply in the absence of a
  /// [BoxConstraints.maxWidth] constraint.
  final double maxWidth;

  final JsonWidgetData? child;
}

/* AUTOGENERATED FROM [LimitedBox]*/
/// Creates a box that limits its size only when it's unconstrained.
///
/// The [maxWidth] and [maxHeight] arguments must not be negative.
class JsonLimitedBoxBuilderModel extends JsonWidgetBuilderModel {
  const JsonLimitedBoxBuilderModel(
    super.args, {
    this.maxHeight = double.infinity,
    this.maxWidth = double.infinity,
    this.child,
  });

  /* AUTOGENERATED FROM [LimitedBox.maxHeight]*/
  /// The maximum height limit to apply in the absence of a
  /// [BoxConstraints.maxHeight] constraint.
  final double maxHeight;

  /* AUTOGENERATED FROM [LimitedBox.maxWidth]*/
  /// The maximum width limit to apply in the absence of a
  /// [BoxConstraints.maxWidth] constraint.
  final double maxWidth;

  final JsonWidgetData? child;

  static JsonLimitedBoxBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[JsonLimitedBoxBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static JsonLimitedBoxBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    JsonLimitedBoxBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is JsonLimitedBoxBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = JsonLimitedBoxBuilderModel(
          args,
          maxHeight: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['maxHeight']);

            parsed ??= double.infinity;

            return parsed;
          }(),
          maxWidth: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['maxWidth']);

            parsed ??= double.infinity;

            return parsed;
          }(),
          child: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['child'],
              registry: registry,
            );

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'maxHeight': double.infinity == maxHeight ? null : maxHeight,
      'maxWidth': double.infinity == maxWidth ? null : maxWidth,
      'child': child?.toJson(),

      ...args,
    });
  }
}

class LimitedBoxSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/limited_box.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'LimitedBox',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'maxHeight': SchemaHelper.numberSchema,
      'maxWidth': SchemaHelper.numberSchema,
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
    'required': [],
  };
}
