// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_data_table_theme_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class JsonDataTableThemeBuilder extends _JsonDataTableThemeBuilder {
  const JsonDataTableThemeBuilder({required super.args});

  static const kType = 'data_table_theme';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static JsonDataTableThemeBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => JsonDataTableThemeBuilder(args: map);

  @override
  JsonDataTableThemeBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = JsonDataTableThemeBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  DataTableTheme buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return DataTableTheme(
      data: model.data,
      key: key,
      child: model.child.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonDataTableTheme extends JsonWidgetData {
  JsonDataTableTheme({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    required this.data,
    required this.child,
  }) : super(
         jsonWidgetArgs: JsonDataTableThemeBuilderModel.fromDynamic(
           {'data': data, 'child': child, ...args},
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder:
             () => JsonDataTableThemeBuilder(
               args: JsonDataTableThemeBuilderModel.fromDynamic(
                 {'data': data, 'child': child, ...args},
                 args: args,
                 registry: registry,
               ),
             ),
         jsonWidgetType: JsonDataTableThemeBuilder.kType,
       );

  /* AUTOGENERATED FROM [DataTableTheme.data]*/
  /// The properties used for all descendant [DataTable] widgets.
  final DataTableThemeData data;

  final JsonWidgetData child;
}

/* AUTOGENERATED FROM [DataTableTheme]*/
/// Constructs a data table theme that configures all descendant
/// [DataTable] widgets.
class JsonDataTableThemeBuilderModel extends JsonWidgetBuilderModel {
  const JsonDataTableThemeBuilderModel(
    super.args, {
    required this.data,
    required this.child,
  });

  /* AUTOGENERATED FROM [DataTableTheme.data]*/
  /// The properties used for all descendant [DataTable] widgets.
  final DataTableThemeData data;

  final JsonWidgetData child;

  static JsonDataTableThemeBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[JsonDataTableThemeBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static JsonDataTableThemeBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    JsonDataTableThemeBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is JsonDataTableThemeBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = JsonDataTableThemeBuilderModel(
          args,
          data: () {
            dynamic parsed = ThemeDecoder.decodeDataTableThemeData(
              map['data'],
              validate: false,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [data].',
              );
            }
            return parsed;
          }(),
          child: () {
            dynamic parsed = JsonWidgetData.fromDynamic(
              map['child'],
              registry: registry,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [child].',
              );
            }
            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'data': ThemeEncoder.encodeDataTableThemeData(data),
      'child': child.toJson(),

      ...args,
    });
  }
}

class DataTableThemeSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/data_table_theme.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'DataTableTheme',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'data': SchemaHelper.objectSchema(DataTableThemeDataSchema.id),
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
    'required': ['data', 'child'],
  };
}
