// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_animated_padding_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class JsonAnimatedPaddingBuilder extends _JsonAnimatedPaddingBuilder {
  const JsonAnimatedPaddingBuilder({required super.args});

  static const kType = 'animated_padding';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static JsonAnimatedPaddingBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => JsonAnimatedPaddingBuilder(args: map);

  @override
  JsonAnimatedPaddingBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = JsonAnimatedPaddingBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  AnimatedPadding buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return AnimatedPadding(
      curve: model.curve,
      duration: model.duration,
      key: key,
      onEnd: model.onEnd,
      padding: model.padding,
      child: model.child?.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonAnimatedPadding extends JsonWidgetData {
  JsonAnimatedPadding({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.curve = Curves.linear,
    required this.duration,
    this.onEnd,
    required this.padding,
    this.child,
  }) : super(
         jsonWidgetArgs: JsonAnimatedPaddingBuilderModel.fromDynamic(
           {
             'curve': curve,
             'duration': duration,
             'onEnd': onEnd,
             'padding': padding,
             'child': child,

             ...args,
           },
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder:
             () => JsonAnimatedPaddingBuilder(
               args: JsonAnimatedPaddingBuilderModel.fromDynamic(
                 {
                   'curve': curve,
                   'duration': duration,
                   'onEnd': onEnd,
                   'padding': padding,
                   'child': child,

                   ...args,
                 },
                 args: args,
                 registry: registry,
               ),
             ),
         jsonWidgetType: JsonAnimatedPaddingBuilder.kType,
       );

  final Curve curve;

  final Duration duration;

  final void Function()? onEnd;

  /* AUTOGENERATED FROM [AnimatedPadding.padding]*/
  /// The amount of space by which to inset the child.
  final EdgeInsetsGeometry padding;

  /* AUTOGENERATED FROM [AnimatedPadding.child]*/
  /// The widget below this widget in the tree.
  ///
  /// {@macro flutter.widgets.ProxyWidget.child}
  final JsonWidgetData? child;
}

/* AUTOGENERATED FROM [AnimatedPadding]*/
/// Creates a widget that insets its child by a value that animates
/// implicitly.
class JsonAnimatedPaddingBuilderModel extends JsonWidgetBuilderModel {
  const JsonAnimatedPaddingBuilderModel(
    super.args, {
    this.curve = Curves.linear,
    required this.duration,
    this.onEnd,
    required this.padding,
    this.child,
  });

  final Curve curve;

  final Duration duration;

  final void Function()? onEnd;

  /* AUTOGENERATED FROM [AnimatedPadding.padding]*/
  /// The amount of space by which to inset the child.
  final EdgeInsetsGeometry padding;

  /* AUTOGENERATED FROM [AnimatedPadding.child]*/
  /// The widget below this widget in the tree.
  ///
  /// {@macro flutter.widgets.ProxyWidget.child}
  final JsonWidgetData? child;

  static JsonAnimatedPaddingBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[JsonAnimatedPaddingBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static JsonAnimatedPaddingBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    JsonAnimatedPaddingBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is JsonAnimatedPaddingBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = JsonAnimatedPaddingBuilderModel(
          args,
          curve: () {
            dynamic parsed = CurvesValues.lookup(map['curve']);

            parsed ??= Curves.linear;

            return parsed;
          }(),
          duration: () {
            dynamic parsed = JsonClass.parseDurationFromMillis(map['duration']);

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [duration].',
              );
            }
            return parsed;
          }(),
          onEnd: map['onEnd'],
          padding: () {
            dynamic parsed = ThemeDecoder.decodeEdgeInsetsGeometry(
              map['padding'],
              validate: false,
            );

            if (parsed == null) {
              throw Exception(
                'Null value encountered for required parameter: [padding].',
              );
            }
            return parsed;
          }(),
          child: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['child'],
              registry: registry,
            );

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'curve': Curves.linear == curve ? null : CurvesValues.encode(curve),
      'duration': duration.inMilliseconds,
      'onEnd': onEnd,
      'padding': ThemeEncoder.encodeEdgeInsetsGeometry(padding),
      'child': child?.toJson(),

      ...args,
    });
  }
}

class AnimatedPaddingSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/animated_padding.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'AnimatedPadding',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'curve': SchemaHelper.anySchema,
      'duration': SchemaHelper.anySchema,
      'onEnd': SchemaHelper.anySchema,
      'padding': SchemaHelper.objectSchema(EdgeInsetsGeometrySchema.id),
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
    'required': ['duration', 'padding'],
  };
}
