// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'json_sized_box_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class JsonSizedBoxBuilder extends _JsonSizedBoxBuilder {
  const JsonSizedBoxBuilder({required super.args});

  static const kType = 'sized_box';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static JsonSizedBoxBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) => JsonSizedBoxBuilder(args: map);

  @override
  JsonSizedBoxBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = JsonSizedBoxBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  SizedBox buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(childBuilder: childBuilder, data: data);

    return SizedBox(
      height: model.height,
      key: key,
      width: model.width,
      child: model.child?.build(childBuilder: childBuilder, context: context),
    );
  }
}

class JsonSizedBox extends JsonWidgetData {
  JsonSizedBox({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.height,
    this.width,
    this.child,
  }) : super(
         jsonWidgetArgs: JsonSizedBoxBuilderModel.fromDynamic(
           {'height': height, 'width': width, 'child': child, ...args},
           args: args,
           registry: registry,
         ),
         jsonWidgetBuilder:
             () => JsonSizedBoxBuilder(
               args: JsonSizedBoxBuilderModel.fromDynamic(
                 {'height': height, 'width': width, 'child': child, ...args},
                 args: args,
                 registry: registry,
               ),
             ),
         jsonWidgetType: JsonSizedBoxBuilder.kType,
       );

  /* AUTOGENERATED FROM [SizedBox.height]*/
  /// If non-null, requires the child to have exactly this height.
  final double? height;

  /* AUTOGENERATED FROM [SizedBox.width]*/
  /// If non-null, requires the child to have exactly this width.
  final double? width;

  final JsonWidgetData? child;
}

/* AUTOGENERATED FROM [SizedBox]*/
/// Creates a fixed size box. The [width] and [height] parameters can be null
/// to indicate that the size of the box should not be constrained in
/// the corresponding dimension.
class JsonSizedBoxBuilderModel extends JsonWidgetBuilderModel {
  const JsonSizedBoxBuilderModel(
    super.args, {
    this.height,
    this.width,
    this.child,
  });

  /* AUTOGENERATED FROM [SizedBox.height]*/
  /// If non-null, requires the child to have exactly this height.
  final double? height;

  /* AUTOGENERATED FROM [SizedBox.width]*/
  /// If non-null, requires the child to have exactly this width.
  final double? width;

  final JsonWidgetData? child;

  static JsonSizedBoxBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(map, args: args, registry: registry);

    if (result == null) {
      throw Exception(
        '[JsonSizedBoxBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static JsonSizedBoxBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    JsonSizedBoxBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(map, normalize: true);
      }

      if (map is JsonSizedBoxBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = JsonSizedBoxBuilderModel(
          args,
          height: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['height']);

            return parsed;
          }(),
          width: () {
            dynamic parsed = JsonClass.maybeParseDouble(map['width']);

            return parsed;
          }(),
          child: () {
            dynamic parsed = JsonWidgetData.maybeFromDynamic(
              map['child'],
              registry: registry,
            );

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'height': height,
      'width': width,
      'child': child?.toJson(),

      ...args,
    });
  }
}

class SizedBoxSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/json_dynamic_widget/sized_box.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'SizedBox',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'height': SchemaHelper.numberSchema,
      'width': SchemaHelper.numberSchema,
      'child': SchemaHelper.objectSchema(JsonWidgetDataSchema.id),
    },
    'required': [],
  };
}
